version: '3.8'

services:
  prod:
    container_name: dolima-game-service-prod
    image: registry.gitlab.laiterieduberger.sn:5050/it/dolima-game-service:prod
    build:
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - "3001:3000"
      - "9229:9229"
    networks:
      - dolima-game-service

    volumes:
      - /usr/src/rearing/node_modules
    restart: unless-stopped

networks:
  dolima-game-service:
    driver: bridge
